[package]
name = "file_clipper"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.29.0"
serde = { version = "1.0", features = [
  "derive",
] } # For serialization/deserialization (e.g., for history)
tempfile = "3.19.1" # For creating temporary files
fs_extra = "1.3.0" # For more advanced file system operations (copying with metadata)
shellexpand = "3.1.1" # For expanding tilde in paths
uuid = { version = "1.16", features = [
  "v4",
  "serde",
] } # For generating unique filenames
toml = "0.8.20"
chrono = "0.4.40"
serde_with = "3.12.0"
strum_macros = "0.27.1"
thiserror = "2.0.12"
color-eyre = "0.6.5"
glob = "0.3.2"
