[package]
name = "file_clipper"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.29.0"
serde = { version = "1.0", features = ["derive"] }
fs_extra = "1.3.0"
uuid = { version = "1.16", features = ["v4", "serde"] }
toml = "0.8.20"
chrono = "0.4.40"
serde_with = "3.12.0"
strum_macros = "0.27.1"
thiserror = "2.0.12"
color-eyre = "0.6.5"
glob = "0.3.2"
clap = { version = "4.5.4", features = ["derive"] }

[dev-dependencies]
serial_test = "3.2.0"
tempfile = "3.20.0"
